services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./TherapeutKalendar.AppHost/db/init:/docker-entrypoint-initdb.d

  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile.dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      - postgres

  terminservice:
    build:
      context: .
      dockerfile: TerminService/Dockerfile.dockerfile
    environment:
      AUTH_SERVICE_URL: http://authservice:8080
      ConnectionStrings__postgres: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=postgres;Password=${POSTGRES_PASSWORD};SslMode=Disable"
    ports:
      - "${TERMIN_SERVICE_PORT}:8080"
    depends_on:
      - postgres
      - authservice
  wasm:
    build:
      context: .
      dockerfile: Client.WASM/Dockerfile.dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      TERMIN_SERVICE_URL: http://terminservice:8081
      AUTH_SERVICE_URL: http://authservice:8080
    ports:
      - "${WASM_PORT}:80"
    depends_on:
      - terminservice
      - authservice

volumes:
  pgdata:
  pgadmin_data: