//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open-source, cross-platform 3D printer management software powered by Blazor Hybrid. &lt;strong&gt;Still under development—use at your own risk.&lt;/strong&gt;&lt;/br&gt;Special thanks to &lt;a href=&quot;https://mrhide.de&quot;&gt;MrHide&lt;/a&gt; for the digital logo and Paleva (@x-hain) for her invaluable support.  The source code is available &lt;a href=&quot;https://github.com/akinbender/MakerPrompt&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        public static string AboutPage_Content {
            get {
                return ResourceManager.GetString("AboutPage_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Extrusion Length (mm).
        /// </summary>
        public static string Calculators_ActualExtrusionLength {
            get {
                return ResourceManager.GetString("Calculators_ActualExtrusionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt Pitch (mm).
        /// </summary>
        public static string Calculators_BeltPitch {
            get {
                return ResourceManager.GetString("Calculators_BeltPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belt Steps per Millimeter Calculator.
        /// </summary>
        public static string Calculators_BeltSteps {
            get {
                return ResourceManager.GetString("Calculators_BeltSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current E-steps (steps/mm).
        /// </summary>
        public static string Calculators_CurrentEsteps {
            get {
                return ResourceManager.GetString("Calculators_CurrentEsteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         &lt;h5&gt;How to use:&lt;/h5&gt;        &lt;ol&gt;            &lt;li&gt;Mark 120mm from your extruder entrance&lt;/li&gt;            &lt;li&gt;Heat up your hotend&lt;/li&gt;            &lt;li&gt;Extrude 100mm (use &lt;code&gt;G1 E100 F100&lt;/code&gt;)&lt;/li&gt;            &lt;li&gt;Measure remaining filament to extruder&lt;/li&gt;            &lt;li&gt;Enter values above (actual = 120 - remaining)&lt;/li&gt;        &lt;/ol&gt;.
        /// </summary>
        public static string Calculators_Esteps_HowTo {
            get {
                return ResourceManager.GetString("Calculators_Esteps_HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Steps Calculator.
        /// </summary>
        public static string Calculators_ExtruderSteps {
            get {
                return ResourceManager.GetString("Calculators_ExtruderSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code Example.
        /// </summary>
        public static string Calculators_GCodeExample {
            get {
                return ResourceManager.GetString("Calculators_GCodeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Ratio.
        /// </summary>
        public static string Calculators_GearRatio {
            get {
                return ResourceManager.GetString("Calculators_GearRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadscrew Pitch (mm/revolution).
        /// </summary>
        public static string Calculators_LeadscrewPitch {
            get {
                return ResourceManager.GetString("Calculators_LeadscrewPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadscrew Steps per Millimeter Calculator.
        /// </summary>
        public static string Calculators_LeadScrewSteps {
            get {
                return ResourceManager.GetString("Calculators_LeadScrewSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure with a caliper.
        /// </summary>
        public static string Calculators_MeasureCaliper {
            get {
                return ResourceManager.GetString("Calculators_MeasureCaliper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Microsteppin.
        /// </summary>
        public static string Calculators_Microstepping {
            get {
                return ResourceManager.GetString("Calculators_Microstepping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Step Angle.
        /// </summary>
        public static string Calculators_MotorAngle {
            get {
                return ResourceManager.GetString("Calculators_MotorAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print price Calculator.
        /// </summary>
        public static string Calculators_PrintPrice {
            get {
                return ResourceManager.GetString("Calculators_PrintPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulley Tooth Count.
        /// </summary>
        public static string Calculators_PulleyToothCount {
            get {
                return ResourceManager.GetString("Calculators_PulleyToothCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to save after testing.
        /// </summary>
        public static string Calculators_RememberSave {
            get {
                return ResourceManager.GetString("Calculators_RememberSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Extrusion Length (mm).
        /// </summary>
        public static string Calculators_RequestedExtrusionLength {
            get {
                return ResourceManager.GetString("Calculators_RequestedExtrusionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Calculators_Resolution {
            get {
                return ResourceManager.GetString("Calculators_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps per mm.
        /// </summary>
        public static string Calculators_Steps {
            get {
                return ResourceManager.GetString("Calculators_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heater Index.
        /// </summary>
        public static string CalibrationPage_HeaterIndex {
            get {
                return ResourceManager.GetString("CalibrationPage_HeaterIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID Tuning.
        /// </summary>
        public static string CalibrationPage_PidTuning {
            get {
                return ResourceManager.GetString("CalibrationPage_PidTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string CalibrationPage_Result {
            get {
                return ResourceManager.GetString("CalibrationPage_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CalibrationPage_Start {
            get {
                return ResourceManager.GetString("CalibrationPage_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal Model.
        /// </summary>
        public static string CalibrationPage_ThermalModel {
            get {
                return ResourceManager.GetString("CalibrationPage_ThermalModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CheatSheetPage_None {
            get {
                return ResourceManager.GetString("CheatSheetPage_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search commands...
        /// </summary>
        public static string CheatSheetPage_SearchCommands {
            get {
                return ResourceManager.GetString("CheatSheetPage_SearchCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established..
        /// </summary>
        public static string CommandPrompt_ConnectedMessage {
            get {
                return ResourceManager.GetString("CommandPrompt_ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy command.
        /// </summary>
        public static string CommandPrompt_CopyCommand {
            get {
                return ResourceManager.GetString("CommandPrompt_CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection terminated..
        /// </summary>
        public static string CommandPrompt_DisconnectedMessage {
            get {
                return ResourceManager.GetString("CommandPrompt_DisconnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter command...
        /// </summary>
        public static string CommandPrompt_EnterCommand {
            get {
                return ResourceManager.GetString("CommandPrompt_EnterCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending command: {0}..
        /// </summary>
        public static string CommandPrompt_ErrorMessage {
            get {
                return ResourceManager.GetString("CommandPrompt_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run command.
        /// </summary>
        public static string CommandPrompt_RunCommand {
            get {
                return ResourceManager.GetString("CommandPrompt_RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string CommandPrompt_Send {
            get {
                return ResourceManager.GetString("CommandPrompt_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string ControlPanel_Current {
            get {
                return ResourceManager.GetString("ControlPanel_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrude.
        /// </summary>
        public static string ControlPanel_Extrude {
            get {
                return ResourceManager.GetString("ControlPanel_Extrude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan speed.
        /// </summary>
        public static string ControlPanel_FanSpeed {
            get {
                return ResourceManager.GetString("ControlPanel_FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating.
        /// </summary>
        public static string ControlPanel_Heating {
            get {
                return ResourceManager.GetString("ControlPanel_Heating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home all.
        /// </summary>
        public static string ControlPanel_HomeAll {
            get {
                return ResourceManager.GetString("ControlPanel_HomeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home selected axis.
        /// </summary>
        public static string ControlPanel_HomeSelected {
            get {
                return ResourceManager.GetString("ControlPanel_HomeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string ControlPanel_Length {
            get {
                return ResourceManager.GetString("ControlPanel_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motors off.
        /// </summary>
        public static string ControlPanel_MotorsOff {
            get {
                return ResourceManager.GetString("ControlPanel_MotorsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ControlPanel_Position {
            get {
                return ResourceManager.GetString("ControlPanel_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print flow.
        /// </summary>
        public static string ControlPanel_PrintFlow {
            get {
                return ResourceManager.GetString("ControlPanel_PrintFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print speed.
        /// </summary>
        public static string ControlPanel_PrintSpeed {
            get {
                return ResourceManager.GetString("ControlPanel_PrintSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string ControlPanel_Reverse {
            get {
                return ResourceManager.GetString("ControlPanel_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not present.
        /// </summary>
        public static string ControlPanel_SdCard_NotPresent {
            get {
                return ResourceManager.GetString("ControlPanel_SdCard_NotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ControlPanel_SdCard_Ready {
            get {
                return ResourceManager.GetString("ControlPanel_SdCard_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string ControlPanel_Set {
            get {
                return ResourceManager.GetString("ControlPanel_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set fan speed.
        /// </summary>
        public static string ControlPanel_Set_FanSpeed {
            get {
                return ResourceManager.GetString("ControlPanel_Set_FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set speed for X &amp; Y axes (mm/min).
        /// </summary>
        public static string ControlPanel_Set_XYSpeed {
            get {
                return ResourceManager.GetString("ControlPanel_Set_XYSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set speed for Z axis (mm/min).
        /// </summary>
        public static string ControlPanel_Set_ZSpeed {
            get {
                return ResourceManager.GetString("ControlPanel_Set_ZSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bed temperature.
        /// </summary>
        public static string ControlPanel_SetBedTemp {
            get {
                return ResourceManager.GetString("ControlPanel_SetBedTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set hotend temperature.
        /// </summary>
        public static string ControlPanel_SetHotendTemp {
            get {
                return ResourceManager.GetString("ControlPanel_SetHotendTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string ControlPanel_Speed {
            get {
                return ResourceManager.GetString("ControlPanel_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ControlPanel_Status {
            get {
                return ResourceManager.GetString("ControlPanel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string ControlPanel_Target {
            get {
                return ResourceManager.GetString("ControlPanel_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string Dashboard_ControlPanel {
            get {
                return ResourceManager.GetString("Dashboard_ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Dashboard_FileExplorer {
            get {
                return ResourceManager.GetString("Dashboard_FileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string Files_DateModified {
            get {
                return ResourceManager.GetString("Files_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Files_Name {
            get {
                return ResourceManager.GetString("Files_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Files_Refresh {
            get {
                return ResourceManager.GetString("Files_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Files_Size {
            get {
                return ResourceManager.GetString("Files_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string GCodeCategory_Calibration {
            get {
                return ResourceManager.GetString("GCodeCategory_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string GCodeCategory_Fan {
            get {
                return ResourceManager.GetString("GCodeCategory_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string GCodeCategory_Movement {
            get {
                return ResourceManager.GetString("GCodeCategory_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string GCodeCategory_Reporting {
            get {
                return ResourceManager.GetString("GCodeCategory_Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sd Card.
        /// </summary>
        public static string GCodeCategory_SdCard {
            get {
                return ResourceManager.GetString("GCodeCategory_SdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string GCodeCategory_Settings {
            get {
                return ResourceManager.GetString("GCodeCategory_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string GCodeCategory_Temperature {
            get {
                return ResourceManager.GetString("GCodeCategory_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string GCodeCommand_Category {
            get {
                return ResourceManager.GetString("GCodeCommand_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string GCodeCommand_Command {
            get {
                return ResourceManager.GetString("GCodeCommand_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GCodeCommand_Description {
            get {
                return ResourceManager.GetString("GCodeCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string GCodeCommand_Parameter {
            get {
                return ResourceManager.GetString("GCodeCommand_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles (3-20).
        /// </summary>
        public static string GCodeDescription_C_Cycle {
            get {
                return ResourceManager.GetString("GCodeDescription_C_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative Value.
        /// </summary>
        public static string GCodeDescription_D_Derivative {
            get {
                return ResourceManager.GetString("GCodeDescription_D_Derivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrude amount.
        /// </summary>
        public static string GCodeDescription_E_Amount {
            get {
                return ResourceManager.GetString("GCodeDescription_E_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Position.
        /// </summary>
        public static string GCodeDescription_E_Position {
            get {
                return ResourceManager.GetString("GCodeDescription_E_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedrate.
        /// </summary>
        public static string GCodeDescription_F_Feedrate {
            get {
                return ResourceManager.GetString("GCodeDescription_F_Feedrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string GCodeDescription_F_File {
            get {
                return ResourceManager.GetString("GCodeDescription_F_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid linear movement (non-printing).
        /// </summary>
        public static string GCodeDescription_G0 {
            get {
                return ResourceManager.GetString("GCodeDescription_G0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled linear movement (printing).
        /// </summary>
        public static string GCodeDescription_G1 {
            get {
                return ResourceManager.GetString("GCodeDescription_G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home all or specified axes.
        /// </summary>
        public static string GCodeDescription_G28 {
            get {
                return ResourceManager.GetString("GCodeDescription_G28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto bed leveling.
        /// </summary>
        public static string GCodeDescription_G29 {
            get {
                return ResourceManager.GetString("GCodeDescription_G29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set absolute positioning mode.
        /// </summary>
        public static string GCodeDescription_G90 {
            get {
                return ResourceManager.GetString("GCodeDescription_G90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set relative positioning mode.
        /// </summary>
        public static string GCodeDescription_G91 {
            get {
                return ResourceManager.GetString("GCodeDescription_G91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set current position (reset coordinates).
        /// </summary>
        public static string GCodeDescription_G92 {
            get {
                return ResourceManager.GetString("GCodeDescription_G92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral Value.
        /// </summary>
        public static string GCodeDescription_I_Integral {
            get {
                return ResourceManager.GetString("GCodeDescription_I_Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set hotend temperature (non-blocking).
        /// </summary>
        public static string GCodeDescription_M104 {
            get {
                return ResourceManager.GetString("GCodeDescription_M104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report current temperatures.
        /// </summary>
        public static string GCodeDescription_M105 {
            get {
                return ResourceManager.GetString("GCodeDescription_M105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set fan speed (S: 0-255).
        /// </summary>
        public static string GCodeDescription_M106 {
            get {
                return ResourceManager.GetString("GCodeDescription_M106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn fan off.
        /// </summary>
        public static string GCodeDescription_M107 {
            get {
                return ResourceManager.GetString("GCodeDescription_M107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set hotend temp &amp; wait (blocking).
        /// </summary>
        public static string GCodeDescription_M109 {
            get {
                return ResourceManager.GetString("GCodeDescription_M109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        public static string GCodeDescription_M112 {
            get {
                return ResourceManager.GetString("GCodeDescription_M112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current position.
        /// </summary>
        public static string GCodeDescription_M114 {
            get {
                return ResourceManager.GetString("GCodeDescription_M114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get firmware info.
        /// </summary>
        public static string GCodeDescription_M115 {
            get {
                return ResourceManager.GetString("GCodeDescription_M115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set LCD Message.
        /// </summary>
        public static string GCodeDescription_M117 {
            get {
                return ResourceManager.GetString("GCodeDescription_M117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bed temperature (non-blocking).
        /// </summary>
        public static string GCodeDescription_M140 {
            get {
                return ResourceManager.GetString("GCodeDescription_M140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Steppers.
        /// </summary>
        public static string GCodeDescription_M17 {
            get {
                return ResourceManager.GetString("GCodeDescription_M17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Steppers.
        /// </summary>
        public static string GCodeDescription_M18 {
            get {
                return ResourceManager.GetString("GCodeDescription_M18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bed temp &amp; wait (blocking).
        /// </summary>
        public static string GCodeDescription_M190 {
            get {
                return ResourceManager.GetString("GCodeDescription_M190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List SD card contents.
        /// </summary>
        public static string GCodeDescription_M20 {
            get {
                return ResourceManager.GetString("GCodeDescription_M20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize SD card.
        /// </summary>
        public static string GCodeDescription_M21 {
            get {
                return ResourceManager.GetString("GCodeDescription_M21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release SD card.
        /// </summary>
        public static string GCodeDescription_M22 {
            get {
                return ResourceManager.GetString("GCodeDescription_M22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set or report the feed rate percentage for all G-code moves (X, Y, Z, E axes).
        /// </summary>
        public static string GCodeDescription_M220 {
            get {
                return ResourceManager.GetString("GCodeDescription_M220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set or report the flow rate percentage for E-axis extrusion moves.
        /// </summary>
        public static string GCodeDescription_M221 {
            get {
                return ResourceManager.GetString("GCodeDescription_M221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SD file.
        /// </summary>
        public static string GCodeDescription_M23 {
            get {
                return ResourceManager.GetString("GCodeDescription_M23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/resume SD print.
        /// </summary>
        public static string GCodeDescription_M24 {
            get {
                return ResourceManager.GetString("GCodeDescription_M24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause SD print.
        /// </summary>
        public static string GCodeDescription_M25 {
            get {
                return ResourceManager.GetString("GCodeDescription_M25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set SD read position.
        /// </summary>
        public static string GCodeDescription_M26 {
            get {
                return ResourceManager.GetString("GCodeDescription_M26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report SD print status.
        /// </summary>
        public static string GCodeDescription_M27 {
            get {
                return ResourceManager.GetString("GCodeDescription_M27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start writing to SD card.
        /// </summary>
        public static string GCodeDescription_M28 {
            get {
                return ResourceManager.GetString("GCodeDescription_M28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop writing to SD card.
        /// </summary>
        public static string GCodeDescription_M29 {
            get {
                return ResourceManager.GetString("GCodeDescription_M29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete SD file.
        /// </summary>
        public static string GCodeDescription_M30 {
            get {
                return ResourceManager.GetString("GCodeDescription_M30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set hotend PID.
        /// </summary>
        public static string GCodeDescription_M301 {
            get {
                return ResourceManager.GetString("GCodeDescription_M301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID autotune.
        /// </summary>
        public static string GCodeDescription_M303 {
            get {
                return ResourceManager.GetString("GCodeDescription_M303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bed PID.
        /// </summary>
        public static string GCodeDescription_M304 {
            get {
                return ResourceManager.GetString("GCodeDescription_M304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal model calibration.
        /// </summary>
        public static string GCodeDescription_M306 {
            get {
                return ResourceManager.GetString("GCodeDescription_M306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file and start print.
        /// </summary>
        public static string GCodeDescription_M32 {
            get {
                return ResourceManager.GetString("GCodeDescription_M32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store settings in EEPROM.
        /// </summary>
        public static string GCodeDescription_M500 {
            get {
                return ResourceManager.GetString("GCodeDescription_M500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read settings from EEPROM.
        /// </summary>
        public static string GCodeDescription_M501 {
            get {
                return ResourceManager.GetString("GCodeDescription_M501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings in memory to their factory defaults.
        /// </summary>
        public static string GCodeDescription_M502 {
            get {
                return ResourceManager.GetString("GCodeDescription_M502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report current settings from EEPROM.
        /// </summary>
        public static string GCodeDescription_M503 {
            get {
                return ResourceManager.GetString("GCodeDescription_M503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate the contents of the EEPROM.
        /// </summary>
        public static string GCodeDescription_M504 {
            get {
                return ResourceManager.GetString("GCodeDescription_M504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or set the steps-per-unit for one or more axes.
        /// </summary>
        public static string GCodeDescription_M92 {
            get {
                return ResourceManager.GetString("GCodeDescription_M92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportional Value.
        /// </summary>
        public static string GCodeDescription_P_Proportional {
            get {
                return ResourceManager.GetString("GCodeDescription_P_Proportional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target temperature.
        /// </summary>
        public static string GCodeDescription_S_TargetTemp {
            get {
                return ResourceManager.GetString("GCodeDescription_S_TargetTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X position.
        /// </summary>
        public static string GCodeDescription_X_Position {
            get {
                return ResourceManager.GetString("GCodeDescription_X_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y position.
        /// </summary>
        public static string GCodeDescription_Y_Position {
            get {
                return ResourceManager.GetString("GCodeDescription_Y_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z position.
        /// </summary>
        public static string GCodeDescription_Z_Position {
            get {
                return ResourceManager.GetString("GCodeDescription_Z_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser not supported..
        /// </summary>
        public static string NavConnection_BrowserNotSupported {
            get {
                return ResourceManager.GetString("NavConnection_BrowserNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string NavConnection_Connect {
            get {
                return ResourceManager.GetString("NavConnection_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service that simulates a functioning 3D printer for demonstration purposes..
        /// </summary>
        public static string NavConnection_DemoServiceDescription {
            get {
                return ResourceManager.GetString("NavConnection_DemoServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string NavConnection_Disconnect {
            get {
                return ResourceManager.GetString("NavConnection_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh ports.
        /// </summary>
        public static string NavConnection_RefreshPorts {
            get {
                return ResourceManager.GetString("NavConnection_RefreshPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select port.
        /// </summary>
        public static string NavConnection_SelectPort {
            get {
                return ResourceManager.GetString("NavConnection_SelectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PageTitle_About {
            get {
                return ResourceManager.GetString("PageTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculators.
        /// </summary>
        public static string PageTitle_Calculators {
            get {
                return ResourceManager.GetString("PageTitle_Calculators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string PageTitle_CommandPrompt {
            get {
                return ResourceManager.GetString("PageTitle_CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Code Cheat Sheet.
        /// </summary>
        public static string PageTitle_GCodeList {
            get {
                return ResourceManager.GetString("PageTitle_GCodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Code Viewer.
        /// </summary>
        public static string PageTitle_GCodeViewer {
            get {
                return ResourceManager.GetString("PageTitle_GCodeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string PageTitle_Homepage {
            get {
                return ResourceManager.GetString("PageTitle_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatbed.
        /// </summary>
        public static string PrinterComponent_Heatbed {
            get {
                return ResourceManager.GetString("PrinterComponent_Heatbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotend.
        /// </summary>
        public static string PrinterComponent_Hotend {
            get {
                return ResourceManager.GetString("PrinterComponent_Hotend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string PrinterStatus_Connected {
            get {
                return ResourceManager.GetString("PrinterStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string PrinterStatus_Disconnected {
            get {
                return ResourceManager.GetString("PrinterStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PrinterStatus_Error {
            get {
                return ResourceManager.GetString("PrinterStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string PrinterStatus_Paused {
            get {
                return ResourceManager.GetString("PrinterStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string PrinterStatus_Printing {
            get {
                return ResourceManager.GetString("PrinterStatus_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Theme_Auto {
            get {
                return ResourceManager.GetString("Theme_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
    }
}
